---
- name: Configurar Loopback33 con IPv6 y link-local
  hosts: csr
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Configurar interfaz Loopback33
      ios_config:
        lines:
          - interface Loopback33
          - ipv6 address 3001:ABCD:ABCD:1::1/128
          - ipv6 address FE80::1 link-local
